
/* H File is generated from smtp.htm by cod2c.exe v3.04 */

#define CGI_SMTP_RTC_Y		0 
#define CGI_SMTP_RTC_M		1 
#define CGI_SMTP_RTC_D		2 
#define CGI_SMTP_RTC_H		3 
#define CGI_SMTP_RTC_MM		4 
#define CGI_SMTP_TM1_EN		5 
#define CGI_SMTP_TM1_ON_EN		6 
#define CGI_SMTP_TM1_ON_H		7 
#define CGI_SMTP_TM1_ON_M		8 
#define CGI_SMTP_TM1_OFF_EN		9 
#define CGI_SMTP_TM1_OFF_H		10 
#define CGI_SMTP_TM1_OFF_M		11 
#define CGI_SMTP_TM1_VAL		12 
#define CGI_SMTP_TM1_SELECT		13 
#define CGI_SMTP_TM1_DISP		14 
#define CGI_SMTP_TM1_SUN		15 
#define CGI_SMTP_TM1_MON		16 
#define CGI_SMTP_TM1_TUE		17 
#define CGI_SMTP_TM1_WED		18 
#define CGI_SMTP_TM1_THU		19 
#define CGI_SMTP_TM1_FRI		20 
#define CGI_SMTP_TM1_SAT		21 
#define CGI_SMTP_TM1_EVE		22 
#define CGI_SMTP_TM2_EN		23 
#define CGI_SMTP_TM2_ON_EN		24 
#define CGI_SMTP_TM2_ON_H		25 
#define CGI_SMTP_TM2_ON_M		26 
#define CGI_SMTP_TM2_OFF_EN		27 
#define CGI_SMTP_TM2_OFF_H		28 
#define CGI_SMTP_TM2_OFF_M		29 
#define CGI_SMTP_TM2_VAL		30 
#define CGI_SMTP_TM2_SELECT		31 
#define CGI_SMTP_TM2_DISP		32 
#define CGI_SMTP_TM2_SUN		33 
#define CGI_SMTP_TM2_MON		34 
#define CGI_SMTP_TM2_TUE		35 
#define CGI_SMTP_TM2_WED		36 
#define CGI_SMTP_TM2_THU		37 
#define CGI_SMTP_TM2_FRI		38 
#define CGI_SMTP_TM2_SAT		39 
#define CGI_SMTP_TM2_EVE		40 
#define CGI_SMTP_TM3_EN		41 
#define CGI_SMTP_TM3_ON_EN		42 
#define CGI_SMTP_TM3_ON_H		43 
#define CGI_SMTP_TM3_ON_M		44 
#define CGI_SMTP_TM3_OFF_EN		45 
#define CGI_SMTP_TM3_OFF_H		46 
#define CGI_SMTP_TM3_OFF_M		47 
#define CGI_SMTP_TM3_VAL		48 
#define CGI_SMTP_TM3_SELECT		49 
#define CGI_SMTP_TM3_DISP		50 
#define CGI_SMTP_TM3_SUN		51 
#define CGI_SMTP_TM3_MON		52 
#define CGI_SMTP_TM3_TUE		53 
#define CGI_SMTP_TM3_WED		54 
#define CGI_SMTP_TM3_THU		55 
#define CGI_SMTP_TM3_FRI		56 
#define CGI_SMTP_TM3_SAT		57 
#define CGI_SMTP_TM3_EVE		58 
#define CGI_SMTP_TM4_EN		59 
#define CGI_SMTP_TM4_ON_EN		60 
#define CGI_SMTP_TM4_ON_H		61 
#define CGI_SMTP_TM4_ON_M		62 
#define CGI_SMTP_TM4_OFF_EN		63 
#define CGI_SMTP_TM4_OFF_H		64 
#define CGI_SMTP_TM4_OFF_M		65 
#define CGI_SMTP_TM4_VAL		66 
#define CGI_SMTP_TM4_SELECT		67 
#define CGI_SMTP_TM4_DISP		68 
#define CGI_SMTP_TM4_SUN		69 
#define CGI_SMTP_TM4_MON		70 
#define CGI_SMTP_TM4_TUE		71 
#define CGI_SMTP_TM4_WED		72 
#define CGI_SMTP_TM4_THU		73 
#define CGI_SMTP_TM4_FRI		74 
#define CGI_SMTP_TM4_SAT		75 
#define CGI_SMTP_TM4_EVE		76 
