
/* H File is generated from telnet.htm by cod2c.exe v3.04 */

#define CGI_TELNET_STB		0 
#define CGI_TELNET_SRC_VAL		1 
#define CGI_TELNET_SRC_SELECT		2 
#define CGI_TELNET_SRC_DISP		3 
#define CGI_TELNET_SYNC		4 
#define CGI_TELNET_PIC_1		5 
#define CGI_TELNET_PIC_2		6 
#define CGI_TELNET_PIC_3		7 
#define CGI_TELNET_PIC_4		8 
#define CGI_TELNET_SM_1		9 
#define CGI_TELNET_SM_2		10 
#define CGI_TELNET_SM_3		11 
#define CGI_TELNET_SM_4		12 
#define CGI_TELNET_BKL		13 
#define CGI_TELNET_TRE		14 
#define CGI_TELNET_CT		15 
#define CGI_TELNET_BAS		16 
#define CGI_TELNET_BR		17 
#define CGI_TELNET_BAL		18 
#define CGI_TELNET_SR		19 
#define CGI_TELNET_VOL		20 
#define CGI_TELNET_COT_1		21 
#define CGI_TELNET_COT_2		22 
#define CGI_TELNET_COT_3		23 
#define CGI_TELNET_COT_4		24 
#define CGI_TELNET_MUT_1		25 
#define CGI_TELNET_MUT_2		26 
#define CGI_TELNET_HUE		27 
#define CGI_TELNET_HDMI_AUDIO		28 
#define CGI_TELNET_HMA_1		29 
#define CGI_TELNET_HMA_2		30 
#define CGI_TELNET_SAT		31 
#define CGI_TELNET_CTB_1		32 
#define CGI_TELNET_CTB_2		33 
#define CGI_TELNET_CTB_3		34 
#define CGI_TELNET_CTB_4		35 
#define CGI_TELNET_ACT_1		36 
#define CGI_TELNET_ACT_2		37 
