C:\KEIL\C51\BIN\LIB51 CREATE  TELNET.LIB
C:\KEIL\C51\BIN\LIB51 ADD obj\telnet.obj to TELNET.LIB

C:\KEIL\C51\BIN\LIB51 CREATE  NETUART.LIB
C:\KEIL\C51\BIN\LIB51 ADD obj\net_uart.obj to NETUART.LIB

C:\KEIL\C51\BIN\LIB51 CREATE  UDP_TEL.LIB
C:\KEIL\C51\BIN\LIB51 ADD obj\udp_tel.obj to UDP_TEL.LIB