
// Tag file is generated from adc.htm by cod2c.exe v3.04 
[adc.htm]  
CGI_SMTP_MAILT1    0
CGI_SMTP_SERVER    1
CGI_SMTP_MAILT2    2
CGI_SMTP_PORT    3
CGI_SMTP_SBUJECT    4
CGI_SMTP_LOGIN_ID    5
CGI_SMTP_FROM    6
CGI_SMTP_PAS    7
CGI_SMTP_ENABLE    8
CGI_SMTP_WK_1    9
CGI_SMTP_WK_2    10
CGI_SMTP_WK_3    11
CGI_SMTP_WK_4    12
CGI_SMTP_WK_5    13
CGI_SMTP_WK_6    14
CGI_SMTP_WK_7    15
CGI_SMTP_WK_8    16
CGI_SMTP_SEND_H    17
CGI_SMTP_SEND_M    18
C_TAGSIZE		21    //TagArray 
